apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '6001'
  spec:
    containers:
    - name: product-service
      image: baseerburney/product-service:latest
      ports:
      - containerPort: 6001
      readinessProbe:
        httpGet:
          path: /health
          port: 6001
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 6001
        initialDelaySeconds: 15
        periodSeconds: 20
