apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '4001'
  spec:
    containers:
    - name: user-service
      image: baseerburney/user-service:latest
      ports:
      - containerPort: 4001
      readinessProbe:
        httpGet:
          path: /health
          port: 4001
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 4001
        initialDelaySeconds: 15
        periodSeconds: 20
