apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5001'
  spec:
    containers:
    - name: order-service
      image: baseerburney/order-service:latest
      ports:
      - containerPort: 5001
      readinessProbe:
        httpGet:
          path: /health
          port: 5001
        initialDelaySeconds: 5
        periodSeconds: 10
      livenessProbe:
        httpGet:
          path: /health
          port: 5001
        initialDelaySeconds: 15
        periodSeconds: 20
